const en = {
  signIn: 'Sign In',
  password: 'Password',
  userName: 'Username',
  changeLanguage: 'Change Language',
  firstName: 'First Name',
  lastName: 'Last Name',
  state: 'State',
  address: 'Address',
  email: 'Email',
  signOut: 'Sign Out',
  profile: 'Profile',
  languageAlertTitle: 'Change Language',
  languageAlertDescription: 'Do you want to change the language to spanish?',
  yes: 'Yes',
  orders: 'Orders',
  inProgress: 'In Progress',
  overdue: 'Overdue',
  inspection: 'Inspection',
  insurance: 'Insurance',
  repair: 'Repair',
  noFiles: 'There are no files to show.',
  noPhotos: 'There are no photos to show.',
  type: 'Type',
  vendor: 'Vendor',
  coordinator: 'Coordinator',
  startDate: 'Start Date',
  endDate: 'End Date',
  vendorBill: 'Vendor Bill',
  new: 'New',
  photo: 'Photo',
  file: 'File',
  attachments: 'Attachments',
  upload: 'Upload',
  save: 'Save',
  changes: 'Changes',
  order: 'Order',
  takePhoto: 'Take a photo',
  chooseGallery: 'Choose from the gallery',
  cancel: 'Cancel',
  selectFile: 'Select a file',
  before: 'Before',
  after: 'After',
  property: 'Property',
  edit: 'Edit',
  changeImage: 'Change Image'
}

export default en
