const en = {
  signIn: 'Sign In',
  password: 'Password',
  userName: 'Username',
  changeLanguage: 'Change Language',
  firstName: 'First Name',
  lastName: 'Last Name',
  state: 'State',
  address: 'Address',
  email: 'Email',
  signOut: 'Sign Out',
  profile: 'Profile',
  languageAlertTitle: 'Change Language',
  languageAlertDescription: 'Do you want to change the language to spanish?',
  yes: 'Yes',
  orders: 'Orders',
  inProgress: 'In Progress',
  pending: 'Pending Completion',
  overdue: 'Overdue',
  inspection: 'Inspection',
  insurance: 'Insurance',
  repair: 'Repair',
  noFiles: 'There are no files to show.',
  noPhotos: 'There are no photos to show.',
  type: 'Type',
  vendor: 'Vendor',
  coordinator: 'Coordinator',
  startDate: 'Start Date',
  endDate: 'End Date',
  vendorBill: 'Vendor Bill',
  new: 'New',
  photos: 'Photos',
  files: 'Files',
  attachments: 'Attachments',
  save: 'Save',
  changes: 'Changes',
  order: 'Order',
  takePhoto: 'Take a Photo',
  chooseGallery: 'Choose from the gallery',
  cancel: 'Cancel',
  selectFile: 'Select a File',
  before: 'Before',
  after: 'After',
  property: 'Property',
  edit: 'Edit',
  changeImage: 'Change Image',
  selectAvatar: 'Select Avatar',
  vendorEndDate: 'Vendor End Date',
  propertyDocuments: 'Property Documents',
  propertyPhotos: 'Property Photos',
  uploadPhotos: 'Upload Photos',
  uploadFiles: 'Upload File',
  savePhotoAlertTitle: 'Save photo as...',
  savePhotoAlertMessage: 'Choose a type to save the photos',
  documents: 'Documents',
  propertyBeforePhotos: 'Property Before Photos',
  propertyInProgressPhotos: 'Property In Progress Photos',
  propertyAfterPhotos: 'Property After Photos',
  uploadError: 'An error has ocurred.',
  search: 'Search',
  emptyFieldsMessage: 'Empty fields',
  emptyFieldsDescription: 'Please fill all fields to proceed.',
  loginErrorMessage: 'Login error',
  loginErrorDescription: 'Verify your username or password.',
  genericErrorMessage: 'Error',
  genericErrorDescription: 'An error has ocurred.',
  otherRepair: 'Other Repair',
  connectionErrorMessage: 'Connection error',
  connectionErrorDescription: 'Please check your network.'
}

export default en
