const en = {
  signIn: 'Sign In',
  password: 'Password',
  userName: 'Username',
  changeLanguage: 'Change Language',
  firstName: 'First Name',
  lastName: 'Last Name',
  state: 'State',
  address: 'Address',
  email: 'Email',
  signOut: 'Sign Out',
  profile: 'Profile',
  languageAlertTitle: 'Change Language',
  languageAlertDescription: 'Do you want to change the language to spanish?',
  yes: 'Yes',
  orders: 'Orders',
  inProgress: 'In Progress',
  pending: 'Pending Completion',
  overdue: 'Overdue',
  inspection: 'Inspection',
  insurance: 'Insurance',
  repair: 'Repair',
  noFiles: 'There are no files to show.',
  noPhotos: 'There are no photos to show.',
  type: 'Type',
  vendor: 'Vendor',
  coordinator: 'Coordinator',
  startDate: 'Start Date',
  endDate: 'Due Date',
  vendorBill: 'Contract Amount',
  new: 'New',
  photos: 'Photos',
  files: 'Files',
  attachments: 'Attachments',
  save: 'Save',
  changes: 'Changes',
  order: 'Order',
  takePhoto: 'Take a Photo',
  chooseGallery: 'Choose from the gallery',
  cancel: 'Cancel',
  selectFile: 'Select a File',
  before: 'Before',
  after: 'After',
  property: 'Property',
  edit: 'Edit',
  changeImage: 'Change Image',
  selectAvatar: 'Select Avatar',
  vendorEndDate: 'Vendor End Date',
  propertyDocuments: 'Property Documents',
  propertyPhotos: 'Property Photos',
  uploadPhotos: 'Upload Photos',
  uploadFiles: 'Upload File',
  savePhotoAlertTitle: 'Save photo as...',
  savePhotoAlertMessage: 'Choose a type to save the photos',
  documents: 'Documents',
  propertyBeforePhotos: 'Property Before Photos',
  propertyInProgressPhotos: 'Property In Progress Photos',
  propertyAfterPhotos: 'Property After Photos',
  uploadError: 'Upload error',
  uploadErrorDescription: 'Something went wrong.',
  search: 'Search',
  searchInput: 'Search ID or order',
  emptyFieldsMessage: 'Empty fields',
  emptyFieldsDescription: 'Please fill all fields to proceed.',
  loginErrorMessage: 'Login error',
  loginErrorDescription: 'Verify your username or password.',
  genericErrorMessage: 'Error',
  genericErrorDescription: 'An error has ocurred.',
  otherRepair: 'Other Repair',
  connectionErrorMessage: 'Connection error',
  connectionErrorDescription: 'Please check your network.',
  noOrders: 'There are no orders to show.',
  shortPasswordMessage: 'Too short password',
  shortPasswordDescrption: 'Your password must contain at least 8 characters.',
  numberPasswordMessage: 'Not valid password',
  numberPasswordDescription: "Your password can't be entirely numeric.",
  invalidEmailMessage: 'Invalid email',
  invalidEmailDescription: 'Please, use a valid email to save.',
  usedMailMessage: 'Email already used',
  usedMailDescription: 'Enter another email to register.',
  usedUsernameMessage: 'Username already used',
  usedUsernameDescription: 'Enter another username to register.',
  successModify: 'Successful update',
  successUploadMessage: 'Successful upload',
  successUploadDescription: 'You will back to the home screen.',
  startUploadMessage: 'Upload started',
  startUploadDescription: 'This may take a while.',
  fileErrorMessage: 'File error',
  fileErrorDescription: 'An error has ocurred when opening the file.',
  completeOrder: 'Complete Order',
  completeOrderAlt: 'Do you want to complete the order?',
  completeOrderDescription: 'Do you want to complete the order? (Some photos need to be uploaded)',
  successComplete: 'The order is successfully complete',
  lowFreeSpace: 'Low free disk storage',
  lowFreeSpaceDescription: 'Keep in mind that some photos may not be taked',
  downloadError: 'Download error',
  photoTaked: 'Photo taked',
  website: 'Web Site',
  selectAll: 'Select all',
  delete: 'Delete',
  deletePhotos: 'Delete photos',
  deletePhotosDescription: 'Do you want to delete the selected photos?',
  backMessage: 'Go Back?',
  backDescription: 'If you go back the uploading might cancel.',
  uploadMessage: 'Upload progress',
  uploadDescription: 'photos completed...',
  storagePermission: 'Nuvote External Storage Permission',
  storagePermissionDescription: 'Nuvote needs to access to your storage to save your photos',
  askLater: 'Ask Me Later',
  wentBackground: 'The app went background',
  wentBackgroundDescription: 'You must resume the uploading',
  stoppedUpload: 'The upload has stopped.',
  stoppedUploadDescription: 'There was an error uploading the last photo. Retry in a few seconds.',
  lockbox: 'Lockbox',
  pendingPhotos: 'You have photos to upload for work order'
}

export default en
