const es = {
  signIn: 'Iniciar Sesión',
  password: 'Contraseña',
  userName: 'Usuario',
  changeLanguage: 'Cambiar Idioma',
  firstName: 'Nombre',
  lastName: 'Apellido',
  state: 'Estado',
  address: 'Dirección',
  email: 'Correo Electrónico',
  signOut: 'Cerrar Sesión',
  profile: 'Perfil',
  languageAlertTitle: 'Cambiar Idioma',
  languageAlertDescription: '¿Desea cambiar el idioma a inglés?',
  yes: 'Sí',
  orders: 'Órdenes',
  inProgress: 'En Proceso',
  overdue: 'Atrasados',
  inspection: 'Inspección',
  insurance: 'Seguro',
  repair: 'Reparación',
  noFiles: 'No hay archivos para mostrar.',
  noPhotos: 'No hay fotos para mostrar.',
  type: 'Tipo',
  vendor: 'Vendedor',
  coordinator: 'Coordinador',
  startDate: 'Fecha de Inicio',
  endDate: 'Fecha Final',
  vendorBill: 'Factura',
  new: 'Nuevo',
  newFem: 'Nueva',
  photos: 'Fotos',
  files: 'Archivos',
  attachments: 'Adjuntos',
  save: 'Guardar',
  changes: 'Cambios',
  order: 'Órden',
  takePhoto: 'Tomar Foto',
  chooseGallery: 'Elegir desde la galería',
  cancel: 'Cancelar',
  selectFile: 'Seleccionar Archivo',
  before: 'Antes',
  after: 'Después',
  property: 'Propiedad',
  edit: 'Editar',
  changeImage: 'Cambiar Imagen',
  selectAvatar: 'Seleccionar Avatar',
  vendorEndDate: 'Fecha Final',
  propertyDocuments: 'Documentos de la Propiedad',
  propertyPhotos: 'Fotos de la Propiedad',
  uploadPhotos: 'Cargar Fotos',
  uploadFiles: 'Cargar Archivos',
  savePhotoAlertTitle: 'Guardar foto como...',
  savePhotoAlertMessage: 'Seleccione un tipo para guardar la foto',
  documents: 'Documentos',
  propertyBeforePhotos: 'Fotos de la propiedad Antes',
  propertyInProgressPhotos: 'Fotos de la propiedad En proceso',
  propertyAfterPhotos: 'Fotos de la propiedad Después',
  uploadError: 'Ha ocurrido un error.',
  search: 'Buscar'
}

export default es
