const es = {
  signIn: 'Iniciar Sesión',
  password: 'Contraseña',
  userName: 'Usuario',
  changeLanguage: 'Cambiar Idioma',
  firstName: 'Nombre',
  lastName: 'Apellido',
  state: 'Estado',
  address: 'Dirección',
  email: 'Correo Electrónico',
  signOut: 'Cerrar Sesión',
  profile: 'Perfil',
  languageAlertTitle: 'Cambiar Idioma',
  languageAlertDescription: '¿Desea cambiar el idioma a inglés?',
  yes: 'Sí',
  orders: 'Órdenes',
  inProgress: 'En Proceso',
  overdue: 'Atrasados',
  inspection: 'Inspección',
  insurance: 'Seguro',
  repair: 'Reparación',
  noFiles: 'No hay archivos para mostrar.',
  noPhotos: 'No hay fotos para mostrar.',
  type: 'Tipo',
  vendor: 'Vendedor',
  coordinator: 'Coordinador',
  startDate: 'Fecha de Inicio',
  endDate: 'Fecha de Termino',
  vendorBill: 'Factura',
  new: 'Nuevo',
  newFem: 'Nueva',
  photo: 'Foto',
  file: 'Archivo',
  attachments: 'Adjuntos',
  upload: 'Subir',
  save: 'Guardar',
  changes: 'Cambios',
  order: 'Órden',
  takePhoto: 'Tomar foto',
  chooseGallery: 'Elegir desde la galería',
  cancel: 'Cancelar',
  selectFile: 'Seleccionar archivo',
  before: 'Antes',
  after: 'Después',
  property: 'Propiedad',
  edit: 'Editar',
  changeImage: 'Cambiar Imagen',
  selectAvatar: 'Seleccionar Avatar'
}

export default es
