const es = {
  signIn: 'Iniciar Sesión',
  password: 'Contraseña',
  userName: 'Usuario',
  changeLanguage: 'Cambiar Idioma',
  firstName: 'Nombre',
  lastName: 'Apellido',
  state: 'Estado',
  address: 'Dirección',
  email: 'Correo Electrónico',
  signOut: 'Cerrar Sesión',
  profile: 'Perfil',
  languageAlertTitle: 'Cambiar Idioma',
  languageAlertDescription: '¿Desea cambiar el idioma a inglés?',
  yes: 'Sí',
  orders: 'Órdenes',
  inProgress: 'En Proceso',
  pending: 'Pendiente de Completar',
  overdue: 'Atrasados',
  inspection: 'Inspección',
  insurance: 'Seguro',
  repair: 'Reparación',
  noFiles: 'No hay archivos para mostrar.',
  noPhotos: 'No hay fotos para mostrar.',
  type: 'Tipo',
  vendor: 'Vendedor',
  coordinator: 'Coordinador',
  startDate: 'Fecha de Inicio',
  endDate: 'Fecha de Vencimiento',
  vendorBill: 'Costo del Contrato',
  new: 'Nuevo',
  newFem: 'Nueva',
  photos: 'Fotos',
  files: 'Archivos',
  attachments: 'Adjuntos',
  save: 'Guardar',
  changes: 'Cambios',
  order: 'Órden',
  takePhoto: 'Tomar Foto',
  chooseGallery: 'Elegir desde la galería',
  cancel: 'Cancelar',
  selectFile: 'Seleccionar Archivo',
  before: 'Antes',
  after: 'Después',
  property: 'Propiedad',
  edit: 'Editar',
  changeImage: 'Cambiar Imagen',
  selectAvatar: 'Seleccionar Avatar',
  vendorEndDate: 'Fecha Final',
  propertyDocuments: 'Documentos de la Propiedad',
  propertyPhotos: 'Fotos de la Propiedad',
  uploadPhotos: 'Cargar Fotos',
  uploadFiles: 'Cargar Archivos',
  savePhotoAlertTitle: 'Guardar foto como...',
  savePhotoAlertMessage: 'Seleccione un tipo para guardar la foto',
  documents: 'Documentos',
  propertyBeforePhotos: 'Fotos de la propiedad Antes',
  propertyInProgressPhotos: 'Fotos de la propiedad En proceso',
  propertyAfterPhotos: 'Fotos de la propiedad Después',
  uploadError: 'Error al cargar las fotos',
  uploadErrorDescription: 'Algo ha salido mal.',
  search: 'Buscar',
  searchInput: 'Buscar ID u orden',
  emptyFieldsMessage: 'Campos vacíos',
  emptyFieldsDescription: 'Favor de rellenar todos los campos.',
  loginErrorMessage: 'Error al iniciar de sesión',
  loginErrorDescription: 'Verifique su usuario y contraseña.',
  errorMessage: 'Error',
  errorDescription: 'Ha ocurrido un error.',
  otherRepair: 'Otras Reparaciones',
  connectionErrorMessage: 'Error de conexión',
  connectionErrorDescription: 'Favor de verificar su red.',
  noOrders: 'No hay ordenes para mostrar.',
  shortPasswordMessage: 'Contraseña muy corta',
  shortPasswordDescrption: 'Su contraseña debe contener al menos 8 caracteres.',
  numberPasswordMessage: 'Contraseña no válida',
  numberPasswordDescription: 'Su contraseña no puede ser totalmente numérica.',
  invalidEmailMessage: 'Correo no válido',
  invalidEmailDescription: 'Favor de usar un correo válido',
  successModify: 'Datos actualizados',
  successUploadMessage: 'Carga exitosa',
  startUploadMessage: 'Carga iniciada',
  startUploadDescription: 'Esto puede tomar un tiempo.',
  genericErrorMessage: 'Error',
  genericErrorDescription: 'Ha ocurrido un error.',
  usedMailMessage: 'Correo en uso',
  usedMailDescription: 'Escoga otro correo para registrar.',
  usedUsernameMessage: 'Usuario en uso',
  usedUsernameDescription: 'Escoga otro usuario para registrar',
  fileErrorMessage: 'Error de archivo',
  fileErrorDescription: 'Ha ocurrido un error al abrir el archivo.',
  completeOrder: 'Completar Orden',
  completeOrderAlt: '¿Desea completar la orden?',
  completeOrderDescription: '¿Desea completar la orden? (Algunas fotos necesitan ser subidas.)',
  successComplete: 'La orden ha sido completada exitosamente'
}

export default es
