# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nuvoteApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nuvoteApp

  target 'nuvoteApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
    pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  end

  target 'nuvoteAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
